# -*- coding: utf-8 -*-
"""Rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmKRWz6_SePXFChCVRau30sI6KJmtXV6
"""

import random

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''

images = [rock, paper, scissors]
def play_game():
  user_choice = int(input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n"))
  if user_choice >= 3 or user_choice < 0:
      print("You typed an invalid number, you lose!")
  else:
      print(images[user_choice])

      computer_choice = random.randint(0, 2)
      print("Computer chose:")
      print(images[computer_choice])


      if user_choice == 0 and computer_choice == 2:
          print("You win!")
      elif computer_choice == 0 and user_choice == 2:
          print("You lose")
      elif computer_choice > user_choice:
          print("You lose")
      elif user_choice > computer_choice:
          print("You win!")
      elif computer_choice == user_choice:
          print("It's a draw")

def main():
    while True:
        play_game()
        user_choice1 = input("Do you want to continue? Type 'yes' or 'no': ").strip().lower()
        if user_choice1 != 'yes':
            print("Thanks for playing!")
            break

if __name__ == "__main__":
    main()